// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqlRmH5UKGMx4AYgGdrBKk_RBLpb7tT8w',
    appId: '1:1090951936709:web:531404ff03456eceb1ceac',
    messagingSenderId: '1090951936709',
    projectId: 'dentist-95d5b',
    authDomain: 'dentist-95d5b.firebaseapp.com',
    storageBucket: 'dentist-95d5b.firebasestorage.app',
    measurementId: 'G-BZDZJR664G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgEXmVeY1e2phn3kAkOpy71C6mAEm1rzE',
    appId: '1:1090951936709:android:37edcb8d29ac3b2db1ceac',
    messagingSenderId: '1090951936709',
    projectId: 'dentist-95d5b',
    storageBucket: 'dentist-95d5b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqlRmH5UKGMx4AYgGdrBKk_RBLpb7tT8w',
    appId: '1:1090951936709:web:95f930216e7fade9b1ceac',
    messagingSenderId: '1090951936709',
    projectId: 'dentist-95d5b',
    authDomain: 'dentist-95d5b.firebaseapp.com',
    storageBucket: 'dentist-95d5b.firebasestorage.app',
    measurementId: 'G-DNHZP9X9SZ',
  );
}



